### ISSUE TITLE
Collection Gui Not Showing

### ISSUE THREAD

**Issue by Pandoroeo** [ChindeaYTB/SkyblockCollectionTracker#1]
Hey! The gui does not seem to be showing for some reason. I am trying to track jungle wood, but it doesn't show up on-screen. I type in /sct track jungle and it says it works. However, it doesn't appear. Even when I try to go mine some jungle wood it doesn't pop up. No idea why.

Log: https://mclo.gs/GJWNeJT
(Yes, I am on the latest version)
Mods are in the log

**Comment by ChindeaOne** [comment]
Thank you for reporting me this issue! It turns out the issue was that the server was looking for "jungle wood" instead of "jungle." This has now been fixed for all wood collections

**Comment by Pandoroeo** [comment]
> Thank you for reporting me this issue! It turns out the issue was that the server was looking for "jungle wood" instead of "jungle." This has now been fixed for all wood collections

Thanks for the response, but it looks like the issue has not been fixed. There hasn't been any new versions of the mod, did you perhaps forget to push the github changes?

**Comment by ChindeaOne** [comment]
Sorry for the wait, i thought the problem was only on my api server, but i hope this time the issue has been solved. I pushed a beta version with the fix. You should be able to use "/sct track jungle" or any other wood variants now.

**Comment by Pandoroeo** [comment]
> Sorry for the wait, i thought the problem was only on my api server, but i hope this time the issue has been solved. I pushed a beta version with the fix. You should be able to use "/sct track jungle" or any other wood variants now.

You're fine. I'm not entirely sure why, but it's still not working for me. I tried jungle and it still didn't work. I then tried coal and wheat and neither of those worked. Additionally, the pause and resume commands don't seem to work (it says unknown command). Thanks for your support so far.

**Comment by ChindeaOne** [comment]
I've identified the issue. I reviewed your account, and no collection is returning any results. Then, I checked SkyCrypt and saw that your API is turned off. You should enable it so the mod can check your collections. It's in Skyblock Menu -> Settings (redstone torch) -> API Settings (comparator top right)

**Comment by Pandoroeo** [comment]
> I've identified the issue. I reviewed your account, and no collection is returning any results. Then, I checked SkyCrypt and saw that your API is turned off. You should enable it so the mod can check your collections. It's in Skyblock Menu -> Settings (redstone torch) -> API Settings (comparator top right)

Thank you so much! I didn't realize this would be needed lol. Have an amazing day!
